### ISSUE TITLE
finishing checklist

### ISSUE THREAD

**Issue by Prasundas99** [Ecstasia-22/Ecstasia-2022-Web#24]
- [ ] Add redirect to public build
- [ ] Change manifeast
- [ ] social icons in prob
- [ ] social icons link
- [ ] nav active will be coloured
- [ ] Bold image desc in gallery
- [ ] Add icons to register and member in single event page
- [ ] change image in single event
- [ ] check all params in single event 
- [ ] Fix team page
- [ ] functional down arrow in hero section
